version: '3'

services:
  postgres:
    image: postgres:9.6
  #  volumes:
  #    - ./docker/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
